name: arc
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - gdal
  - pip
  - netCDF4
  - xarray
  - geojson
  - networkx
  - dask
  - geoglows
  - numba
  - scipy
  - tqdm
  - pyproj
  - fiona
  - netcdf4
  - shapely
  - networkx
  - s3fs


