name: arc
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - fastparquet
  - geopandas
  - gdal
  - pip
  - netCDF4
  - xarray
  - geojson
  - pyyaml
  - networkx
  - dask
  - numba
  - scipy
  - tqdm
  - pyproj
  - shapely
  - s3fs
  - pyproj


